version: '3.1'

services:
  be:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: next-shop-be
    ports:
      - "4000:4000"
    networks:
      - next
  fe:
    build:
      context: ../fe
      dockerfile: ./Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:8000
    container_name: next-shop-fe
    ports:
      - "3000:3000"
  mongo:
    image: mongo:6.0.4
    container_name: next-shop-db
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
    volumes:
      - ./datadir:/data/db
    ports:
      - "27017:27017"
    networks:
      - next
networks:
  next: