version: '3.1'

services:
  mongo:
    image: mongo:6.0.4
    container_name: next-shop-db
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
    volumes:
      - ./datadir:/data/db
    ports:
      - "27017:27017"
